"""Keeps the API's untested surface visible and shrinking.

tests/test_api.py claimed to test "every route for success, 404, 401, and
invalid input paths". It did not -- 28 of the app's 91 routes are not named by
any test at all, and nothing said so. A docstring cannot enforce that; this can.

The check is deliberately shallow: it asks whether a route's path appears
anywhere in the test sources, not whether it is tested well. That is enough to
catch the failure that actually happened -- a whole route group shipping with no
test naming it -- without pretending to measure assertion quality.

KNOWN_UNCOVERED is the debt, written down. It may only shrink: covering a route
without removing it here fails test_the_known_gap_list_has_no_stale_entries, and
adding a route without a test fails test_no_new_routes_go_uncovered.
"""

import glob
import os

import pytest

from api.main import app

# This module lists the uncovered paths verbatim in KNOWN_UNCOVERED, so it must
# not be scanned as evidence that they are tested.
_THIS_FILE = os.path.abspath(__file__)

# Generated by FastAPI itself, not application code, so not test debt.
_FRAMEWORK_ROUTES = frozenset(
    ["/docs", "/docs/oauth2-redirect", "/redoc", "/openapi.json"]
)

# Routes with no test naming them. Grouped by area, roughly by risk.
KNOWN_UNCOVERED = frozenset([
    # admin -- creates backups and restarts the public stack
    ("GET", "/api/v1/admin/backups"),
    ("GET", "/api/v1/admin/backups/{filename}"),
    ("POST", "/api/v1/admin/backups"),
    ("POST", "/api/v1/admin/stack/ensure-public"),
    ("POST", "/api/v1/admin/stack/restart-public"),
    ("POST", "/api/v1/admin/stack/status"),
    # notion -- match/override and override/bulk write override rows
    ("GET", "/api/v1/notion/import/preview"),
    ("GET", "/api/v1/notion/match/review"),
    ("POST", "/api/v1/notion/import/next-batch"),
    ("POST", "/api/v1/notion/match/override"),
    ("POST", "/api/v1/notion/match/override/bulk"),
    # plaud integrations
    ("GET", "/api/v1/plaud/integrations/capabilities"),
    ("GET", "/api/v1/plaud/integrations/embedded/transcriptions/{transcription_id}"),
    ("GET", "/api/v1/plaud/integrations/files/{file_id}/audio"),
    ("GET", "/api/v1/plaud/integrations/mcp/auth/status"),
    ("GET", "/api/v1/plaud/integrations/mcp/tools"),
    ("GET", "/api/v1/plaud/integrations/status"),
    ("POST", "/api/v1/plaud/integrations/embedded/transcriptions"),
    ("POST", "/api/v1/plaud/integrations/embedded/uploads/complete"),
    ("POST", "/api/v1/plaud/integrations/embedded/uploads/presign"),
    ("POST", "/api/v1/plaud/integrations/embedded/user-token"),
    ("POST", "/api/v1/plaud/integrations/mcp/auth/reconnect"),
    ("POST", "/api/v1/plaud/integrations/mcp/tools/{tool_name}"),
    # sync
    ("POST", "/api/v1/sync/upload/process"),
])


def _app_routes():
    """Every (method, path) the app serves, minus framework-generated docs."""
    found = set()
    for route in app.routes:
        path = getattr(route, "path", None)
        methods = getattr(route, "methods", None)
        if not path or not methods or path in _FRAMEWORK_ROUTES:
            continue
        for method in methods - {"HEAD", "OPTIONS"}:
            found.add((method, path))
    return found


def _test_sources():
    return "".join(
        open(f, encoding="utf-8").read()
        for f in glob.glob("tests/**/*.py", recursive=True)
        if os.path.abspath(f) != _THIS_FILE
    )


def _is_named_in_tests(path, sources):
    """True if a test mentions this path, up to its first path parameter."""
    prefix = path.split("{")[0].rstrip("/") or path
    return prefix in sources


@pytest.fixture(scope="module")
def sources():
    return _test_sources()


def test_no_new_routes_go_uncovered(sources):
    """A route added without a test must be covered or consciously listed."""
    uncovered = {
        (m, p) for m, p in _app_routes() if not _is_named_in_tests(p, sources)
    }
    unlisted = uncovered - KNOWN_UNCOVERED

    assert not unlisted, (
        "these routes have no test naming them and are not in KNOWN_UNCOVERED:\n"
        + "\n".join("  %s %s" % r for r in sorted(unlisted))
        + "\n\nWrite a test, or add them to KNOWN_UNCOVERED with a reason."
    )


def test_the_known_gap_list_has_no_stale_entries(sources):
    """KNOWN_UNCOVERED may only shrink -- it must never outlive the real gap."""
    routes = _app_routes()

    gone = {r for r in KNOWN_UNCOVERED if r not in routes}
    assert not gone, (
        "KNOWN_UNCOVERED lists routes the app no longer serves:\n"
        + "\n".join("  %s %s" % r for r in sorted(gone))
        + "\n\nRemove them."
    )

    now_covered = {
        (m, p) for m, p in KNOWN_UNCOVERED if _is_named_in_tests(p, sources)
    }
    assert not now_covered, (
        "these routes are now named by tests -- delete them from KNOWN_UNCOVERED:\n"
        + "\n".join("  %s %s" % r for r in sorted(now_covered))
    )


def test_the_recorded_gap_matches_reality(sources):
    """Report the real numbers, so the debt is a fact rather than a claim."""
    routes = _app_routes()
    uncovered = {
        (m, p) for m, p in routes if not _is_named_in_tests(p, sources)
    }

    assert uncovered == KNOWN_UNCOVERED, (
        "route coverage drifted: %d/%d uncovered, KNOWN_UNCOVERED has %d"
        % (len(uncovered), len(routes), len(KNOWN_UNCOVERED))
    )
